# Set the name of your your application
APPLICATION = Module1

# If no BOARD is found in the environment, use this default
BOARD ?= native

#This has to be the absolute path to the RIOT base directory
RIOTBASE ?= $(CURDIR)/../RIOT

USEMODULE += arduino
include $(RIOTBASE)/Makefile.include
